git pull
rem action_generate_kicad_outputs.py
action_generate_corel_outputs.py
rem action_generate_office_outputs.py
action_generate_resolutions.py
rem action_generate_readme_outputs.py
action_git_commit.py